# Generated by Django 6.0.7 on 2026-09-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desktop_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='migrated_from_offline_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
