# Generated by Django 6.0.7 on 2026-09-21 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('desktop_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_name', models.CharField(max_length=200)),
                ('scientific_name', models.CharField(blank=True, default='', max_length=200)),
                ('category', models.CharField(blank=True, default='', max_length=120)),
                ('quantity', models.IntegerField(default=0)),
                ('buy_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sell_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('shelf_location', models.CharField(blank=True, default='', max_length=120)),
                ('is_damaged', models.BooleanField(default=False)),
                ('barcode', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='desktop_api.pharmacy')),
            ],
            options={
                'indexes': [models.Index(fields=['pharmacy', 'trade_name'], name='pharmacy_da_pharmac_2f18ed_idx'), models.Index(fields=['pharmacy', 'scientific_name'], name='pharmacy_da_pharmac_adce8d_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='medicine_quantity_gte_0'), models.CheckConstraint(condition=models.Q(('buy_price__gte', 0)), name='medicine_buy_price_gte_0'), models.CheckConstraint(condition=models.Q(('sell_price__gte', 0)), name='medicine_sell_price_gte_0')],
            },
        ),
    ]
