# Generated by Django 6.0.7 on 2026-09-23 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desktop_api', '0001_initial'),
        ('pharmacy_data', '0003_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='DamagedMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_damaged', models.PositiveIntegerField()),
                ('reason', models.CharField(blank=True, default='', max_length=32)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('damaged_at', models.DateField(auto_now_add=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='damaged_records', to='pharmacy_data.medicine')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damaged_medicines', to='desktop_api.pharmacy')),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['pharmacy', 'damaged_at'], name='pharmacy_da_pharmac_1fb0c2_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity_damaged__gt', 0)), name='damaged_medicine_quantity_gt_0')],
            },
        ),
    ]
