# Generated by Django 6.0.7 on 2026-09-24 09:27

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy_data', '0004_damagedmedicine'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='cashier_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='damagedmedicine',
            name='damaged_at',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='purchaseinvoicereturn',
            name='returned_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='paid_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
