# Generated by Django 6.0.7 on 2026-10-01 18:34

from django.db import migrations, models


def normalize_empty_barcodes(apps, schema_editor):
    Medicine = apps.get_model("pharmacy_data", "Medicine")
    Medicine.objects.filter(barcode="").update(barcode=None)


class Migration(migrations.Migration):

    dependencies = [
        ('desktop_api', '0003_desktoplicense_plan_pharmacylink'),
        ('pharmacy_data', '0005_invoice_cashier_name_and_more'),
    ]

    operations = [
        migrations.RunPython(normalize_empty_barcodes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='medicine',
            name='barcode',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name='medicine',
            constraint=models.UniqueConstraint(condition=models.Q(('barcode__isnull', False), models.Q(('barcode', ''), _negated=True)), fields=('pharmacy', 'barcode'), name='unique_medicine_barcode_per_pharmacy'),
        ),
    ]
