# Generated by Django 6.0.7 on 2026-10-03 15:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desktop_api', '0004_remove_pharmacylink_desktoplicense_max_warehouses'),
        ('pharmacy_data', '0009_medicine_warehouse_required_stocktransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='damagedmedicine',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='avg_cost',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.CreateModel(
            name='MedicineBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='pharmacy_data.medicine')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_batches', to='desktop_api.pharmacy')),
            ],
            options={
                'ordering': ['expiry_date', 'id'],
                'indexes': [models.Index(fields=['medicine', 'expiry_date'], name='pharmacy_da_medicin_74717e_idx')],
            },
        ),
    ]
