# Generated by Django 6.0.7 on 2026-10-05 20:36
# قيد فرادة رقم فاتورة الشراء يُضاف في 0014 بعد إعادة تسمية المكرر في 0013.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desktop_api', '0004_remove_pharmacylink_desktoplicense_max_warehouses'),
        ('pharmacy_data', '0011_backfill_avg_cost_and_batches'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_name', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('bonus_quantity', models.PositiveIntegerField(default=0)),
                ('buy_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('effective_unit_cost', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('sell_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='medicinebatch',
            name='purchase_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='pharmacy_data.purchaseinvoice'),
        ),
        migrations.AddField(
            model_name='medicinebatch',
            name='source',
            field=models.CharField(blank=True, choices=[('purchase_list', 'قائمة مذخر'), ('opening_stock', 'رصيد افتتاحي')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='medicinebatch',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='pharmacy_data.supplier'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='item_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='source',
            field=models.CharField(choices=[('manual', 'يدوية'), ('inventory_list', 'من قائمة المخزون')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceitem',
            name='medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_items', to='pharmacy_data.medicine'),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceitem',
            name='pharmacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_invoice_items', to='desktop_api.pharmacy'),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceitem',
            name='purchase_invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacy_data.purchaseinvoice'),
        ),
        migrations.AddConstraint(
            model_name='purchaseinvoiceitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0), ('bonus_quantity__gt', 0), _connector='OR'), name='purchase_invoice_item_qty_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='purchaseinvoiceitem',
            constraint=models.CheckConstraint(condition=models.Q(('line_total__gte', 0)), name='purchase_invoice_item_total_gte_0'),
        ),
    ]
