# Generated by Django 6.0.7 on 2026-10-06 13:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desktop_api', '0004_remove_pharmacylink_desktoplicense_max_warehouses'),
        ('pharmacy_data', '0014_purchase_invoice_number_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseInvoiceReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_name', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField()),
                ('credited_quantity', models.PositiveIntegerField(default=0)),
                ('unit_return_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SupplierCreditApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('applied_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['applied_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SupplierRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['received_at', 'id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='purchaseinvoicereturn',
            name='purchase_invoice_return_amount_gt_0',
        ),
        migrations.AddField(
            model_name='purchaseinvoicereturn',
            name='excess_credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddConstraint(
            model_name='purchaseinvoicereturn',
            constraint=models.CheckConstraint(condition=models.Q(('amount_returned__gte', 0)), name='purchase_invoice_return_amount_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='purchaseinvoicereturn',
            constraint=models.CheckConstraint(condition=models.Q(('excess_credit__gte', 0), ('excess_credit__lte', models.F('amount_returned'))), name='purchase_invoice_return_excess_valid'),
        ),
        migrations.AddField(
            model_name='purchaseinvoicereturnitem',
            name='medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_return_items', to='pharmacy_data.medicine'),
        ),
        migrations.AddField(
            model_name='purchaseinvoicereturnitem',
            name='pharmacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_return_items', to='desktop_api.pharmacy'),
        ),
        migrations.AddField(
            model_name='purchaseinvoicereturnitem',
            name='purchase_invoice_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_items', to='pharmacy_data.purchaseinvoiceitem'),
        ),
        migrations.AddField(
            model_name='purchaseinvoicereturnitem',
            name='purchase_return',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacy_data.purchaseinvoicereturn'),
        ),
        migrations.AddField(
            model_name='suppliercreditapplication',
            name='pharmacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_credit_applications', to='desktop_api.pharmacy'),
        ),
        migrations.AddField(
            model_name='suppliercreditapplication',
            name='purchase_invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_applications', to='pharmacy_data.purchaseinvoice'),
        ),
        migrations.AddField(
            model_name='suppliercreditapplication',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_applications', to='pharmacy_data.supplier'),
        ),
        migrations.AddField(
            model_name='supplierrefund',
            name='pharmacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_refunds', to='desktop_api.pharmacy'),
        ),
        migrations.AddField(
            model_name='supplierrefund',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='pharmacy_data.supplier'),
        ),
        migrations.AddConstraint(
            model_name='purchaseinvoicereturnitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='purchase_return_item_qty_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='purchaseinvoicereturnitem',
            constraint=models.CheckConstraint(condition=models.Q(('credited_quantity__lte', models.F('quantity'))), name='purchase_return_item_credited_lte_qty'),
        ),
        migrations.AddConstraint(
            model_name='purchaseinvoicereturnitem',
            constraint=models.CheckConstraint(condition=models.Q(('credit_amount__gte', 0)), name='purchase_return_item_credit_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='suppliercreditapplication',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='supplier_credit_application_amount_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='supplierrefund',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='supplier_refund_amount_gt_0'),
        ),
    ]
